// Initial data extracted directly from Professional_Card_Expense_Tracker_Kitkat_Rashu_v2.xlsx + September additions

const DEFAULT_SETTINGS = {
  "person1": "Kitkat",
  "person2": "Rashu",
  "currencySymbol": "₹",
  "statementDay": 24,
  "paymentDueDay": 13,
  "defaultMonth": "September 2026"
};

const CATEGORIES = [
  "Fuel",
  "Food & Dining",
  "Travel",
  "Shopping",
  "Telecom & Utilities",
  "Fees & Charges",
  "General"
];

const INITIAL_EXPENSES = [
  {
    "id": "july_1",
    "month": "July 2026",
    "date": "07 Jul 26",
    "description": "Car - petrol",
    "slipAmount": 1145.7,
    "statementAmount": 1159.21,
    "fuelWaiver": 11.45,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "july_2",
    "month": "July 2026",
    "date": "09 Jul 26",
    "description": "ASSPL",
    "slipAmount": 0,
    "statementAmount": 1454,
    "fuelWaiver": 0,
    "refundAmount": 1449,
    "usedBy": "Both",
    "paymentType": "Card",
    "category": "Shopping",
    "remarks": ""
  },
  {
    "id": "july_3",
    "month": "July 2026",
    "date": "09 Jul 26",
    "description": "Gift waha mummy",
    "slipAmount": 0,
    "statementAmount": 1504,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Both",
    "paymentType": "Card",
    "category": "Shopping",
    "remarks": ""
  },
  {
    "id": "july_4",
    "month": "July 2026",
    "date": "07 Jul 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 458,
    "statementAmount": 463.4,
    "fuelWaiver": 4.58,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "july_5",
    "month": "July 2026",
    "date": "10 Jul 26",
    "description": "AGARWAL AUTOMOTIVE PR4",
    "slipAmount": 458.28,
    "statementAmount": 462.86,
    "fuelWaiver": 4.58,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "july_6",
    "month": "July 2026",
    "date": "10 Jul 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 343,
    "statementAmount": 347.04,
    "fuelWaiver": 3.43,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "july_7",
    "month": "July 2026",
    "date": "13 Jul 26",
    "description": "RAJA FUELS",
    "slipAmount": 515.57,
    "statementAmount": 521.65,
    "fuelWaiver": 5.15,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "july_8",
    "month": "July 2026",
    "date": "15 Jul 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 343.71,
    "statementAmount": 347.76,
    "fuelWaiver": 3.43,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "july_9",
    "month": "July 2026",
    "date": "17 Jul 26",
    "description": "SHASHIKRISHAN FILLING",
    "slipAmount": 458.28,
    "statementAmount": 463.68,
    "fuelWaiver": 4.58,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "july_10",
    "month": "July 2026",
    "date": "18 Jul 26",
    "description": "AGARWAL AUTOMOTIVE PR4",
    "slipAmount": 515.56,
    "statementAmount": 520.72,
    "fuelWaiver": 5.15,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "july_11",
    "month": "July 2026",
    "date": "19 Jul 26",
    "description": "NIRMAL FILLING STATION",
    "slipAmount": 344,
    "statementAmount": 348.05,
    "fuelWaiver": 3.44,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "july_12",
    "month": "July 2026",
    "date": "23 Jul 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 343.71,
    "statementAmount": 347.76,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "july_13",
    "month": "July 2026",
    "date": "23 Jul 26",
    "description": "NIRMAL FILLING STATION",
    "slipAmount": 458,
    "statementAmount": 463.4,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "july_14",
    "month": "July 2026",
    "date": "24 Jul 26",
    "description": "Annual Fee + GST",
    "slipAmount": 0,
    "statementAmount": 588.82,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fees & Charges",
    "remarks": ""
  },
  {
    "id": "july_15",
    "month": "July 2026",
    "date": "15 Jul 26",
    "description": "Mummy Gift",
    "slipAmount": 1000,
    "statementAmount": 0,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Both",
    "paymentType": "Non-Card",
    "category": "Shopping",
    "remarks": ""
  },
  {
    "id": "aug_1",
    "month": "August 2026",
    "date": "24 Jul 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 458,
    "statementAmount": 463.4,
    "fuelWaiver": 1.58,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_2",
    "month": "August 2026",
    "date": "28 Jul 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 1145.7,
    "statementAmount": 1159.21,
    "fuelWaiver": 11.45,
    "refundAmount": 1000,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_3",
    "month": "August 2026",
    "date": "29 Jul 26",
    "description": "NIRMAL FILLING STATION",
    "slipAmount": 344,
    "statementAmount": 348.05,
    "fuelWaiver": 3.44,
    "refundAmount": 0,
    "usedBy": "Both",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "aug_4",
    "month": "August 2026",
    "date": "29 Jul 26",
    "description": "UPI-U K T 1 Enterprises",
    "slipAmount": 579.61,
    "statementAmount": 579.61,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_5",
    "month": "August 2026",
    "date": "30 Jul 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 1145.7,
    "statementAmount": 1159.21,
    "fuelWaiver": 11.45,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_6",
    "month": "August 2026",
    "date": "30 Jul 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 401,
    "statementAmount": 405.73,
    "fuelWaiver": 4.01,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_7",
    "month": "August 2026",
    "date": "01 Aug 26",
    "description": "MANOJ SHUKLA",
    "slipAmount": 114.57,
    "statementAmount": 115.92,
    "fuelWaiver": 1.14,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_8",
    "month": "August 2026",
    "date": "02 Aug 26",
    "description": "SMART CITY FUELS PR468",
    "slipAmount": 1141,
    "statementAmount": 1152.41,
    "fuelWaiver": 11.41,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "aug_9",
    "month": "August 2026",
    "date": "03 Aug 26",
    "description": "SHASHIKRISHAN FILLING",
    "slipAmount": 515.57,
    "statementAmount": 521.65,
    "fuelWaiver": 5.15,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "aug_10",
    "month": "August 2026",
    "date": "03 Aug 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 343.71,
    "statementAmount": 347.76,
    "fuelWaiver": 3.43,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_11",
    "month": "August 2026",
    "date": "06 Aug 26",
    "description": "SHASHIKRISHAN FILLING",
    "slipAmount": 458.28,
    "statementAmount": 463.68,
    "fuelWaiver": 4.58,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "aug_12",
    "month": "August 2026",
    "date": "06 Aug 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 343.71,
    "statementAmount": 347.76,
    "fuelWaiver": 3.43,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_13",
    "month": "August 2026",
    "date": "07 Aug 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 1145,
    "statementAmount": 1158.51,
    "fuelWaiver": 11.45,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_14",
    "month": "August 2026",
    "date": "08 Aug 26",
    "description": "UPI-NIRMAL FILLING STAT",
    "slipAmount": 115,
    "statementAmount": 115.93,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "aug_15",
    "month": "August 2026",
    "date": "08 Aug 26",
    "description": "Indian Railway Caterin",
    "slipAmount": 4775.62,
    "statementAmount": 4775.62,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "Food & Dining",
    "remarks": ""
  },
  {
    "id": "aug_16",
    "month": "August 2026",
    "date": "08 Aug 26",
    "description": "UPI-DELHI CHOLE BHATURE",
    "slipAmount": 120,
    "statementAmount": 120,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Food & Dining",
    "remarks": ""
  },
  {
    "id": "aug_17",
    "month": "August 2026",
    "date": "08 Aug 26",
    "description": "UPI-Sunil Hashwani",
    "slipAmount": 50,
    "statementAmount": 50,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_18",
    "month": "August 2026",
    "date": "08 Aug 26",
    "description": "UPI-PRAKASH MOBILE",
    "slipAmount": 170,
    "statementAmount": 170,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Shopping",
    "remarks": ""
  },
  {
    "id": "aug_19",
    "month": "August 2026",
    "date": "08 Aug 26",
    "description": "UPI-NASIR MANSURI",
    "slipAmount": 100,
    "statementAmount": 100,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_20",
    "month": "August 2026",
    "date": "08 Aug 26",
    "description": "UPI-DEEPAK KUMAR RATH",
    "slipAmount": 550,
    "statementAmount": 550,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_21",
    "month": "August 2026",
    "date": "08 Aug 26",
    "description": "UPI-New rajhans rubber p work u",
    "slipAmount": 20,
    "statementAmount": 20,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_22",
    "month": "August 2026",
    "date": "08 Aug 26",
    "description": "UPI-KOUSHAL SINGH",
    "slipAmount": 250,
    "statementAmount": 250,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_23",
    "month": "August 2026",
    "date": "08 Aug 26",
    "description": "UPI-BATA",
    "slipAmount": 549,
    "statementAmount": 549,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Shopping",
    "remarks": ""
  },
  {
    "id": "aug_24",
    "month": "August 2026",
    "date": "10 Aug 26",
    "description": "SHASHIKRISHAN FILLING",
    "slipAmount": 515.57,
    "statementAmount": 520.73,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "aug_25",
    "month": "August 2026",
    "date": "12 Aug 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 401,
    "statementAmount": 405.01,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_26",
    "month": "August 2026",
    "date": "12 Aug 26",
    "description": "AGARWAL AUTOMOTIVE PR4",
    "slipAmount": 515.56,
    "statementAmount": 520.72,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "aug_27",
    "month": "August 2026",
    "date": "13 Aug 26",
    "description": "Myjio",
    "slipAmount": 9931.96,
    "statementAmount": 9931.96,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Telecom & Utilities",
    "remarks": ""
  },
  {
    "id": "aug_28",
    "month": "August 2026",
    "date": "14 Aug 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 2291,
    "statementAmount": 2318.03,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_29",
    "month": "August 2026",
    "date": "17 Aug 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 401,
    "statementAmount": 405.01,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_30",
    "month": "August 2026",
    "date": "18 Aug 26",
    "description": "SUDHIR SHARMA",
    "slipAmount": 1145.7,
    "statementAmount": 1157.15,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_31",
    "month": "August 2026",
    "date": "18 Aug 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 1718.55,
    "statementAmount": 1735.73,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_32",
    "month": "August 2026",
    "date": "19 Aug 26",
    "description": "KANTA SHRAWAN MISROD",
    "slipAmount": 343.17,
    "statementAmount": 347.14,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "aug_33",
    "month": "August 2026",
    "date": "19 Aug 26",
    "description": "SHASHIKRISHAN FILLING",
    "slipAmount": 343,
    "statementAmount": 346.43,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "aug_34",
    "month": "August 2026",
    "date": "21 Aug 26",
    "description": "SMART CITY FUELS PR468",
    "slipAmount": 570.7,
    "statementAmount": 576.43,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "aug_35",
    "month": "August 2026",
    "date": "22 Aug 26",
    "description": "SMART CITY FUELS PR468",
    "slipAmount": 570.7,
    "statementAmount": 576.41,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": ""
  },
  {
    "id": "aug_36",
    "month": "August 2026",
    "date": "Aug 2026",
    "description": "Rashu got cash from mosiji",
    "slipAmount": 1000,
    "statementAmount": 1000,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Non-Card",
    "category": "General",
    "remarks": ""
  },
  {
    "id": "sep_1",
    "month": "September 2026",
    "date": "24 Aug 26",
    "description": "Fuel / Card Spend",
    "slipAmount": 572.85,
    "statementAmount": 0,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": "Awaiting 24th Sep Statement"
  },
  {
    "id": "sep_2",
    "month": "September 2026",
    "date": "26 Aug 26",
    "description": "Fuel / Card Spend",
    "slipAmount": 343.71,
    "statementAmount": 0,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Kitkat",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": "Awaiting 24th Sep Statement"
  },
  {
    "id": "sep_3",
    "month": "September 2026",
    "date": "27 Aug 26",
    "description": "Fuel / Card Spend",
    "slipAmount": 458.24,
    "statementAmount": 0,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": "Awaiting 24th Sep Statement"
  },
  {
    "id": "sep_4",
    "month": "September 2026",
    "date": "01 Sep 26",
    "description": "Fuel / Card Spend",
    "slipAmount": 695,
    "statementAmount": 0,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": "Awaiting 24th Sep Statement"
  },
  {
    "id": "sep_5",
    "month": "September 2026",
    "date": "01 Sep 26",
    "description": "Fuel / Card Spend",
    "slipAmount": 515.56,
    "statementAmount": 0,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": "Awaiting 24th Sep Statement"
  },
  {
    "id": "sep_6",
    "month": "September 2026",
    "date": "02 Sep 26",
    "description": "Fuel / Card Spend",
    "slipAmount": 336,
    "statementAmount": 0,
    "fuelWaiver": 0,
    "refundAmount": 0,
    "usedBy": "Rashu",
    "paymentType": "Card",
    "category": "Fuel",
    "remarks": "Awaiting 24th Sep Statement"
  }
];

const INITIAL_PAYMENTS = [
  {
    "id": "pay_jul_1",
    "month": "July 2026",
    "date": "31 Jul 26",
    "person": "Kitkat",
    "amount": 10000,
    "paymentMethod": "Bank Transfer",
    "notes": "Advance settlement payment"
  },
  {
    "id": "pay_jul_2",
    "month": "July 2026",
    "date": "31 Jul 26",
    "person": "Rashu",
    "amount": 4714.99,
    "paymentMethod": "UPI",
    "notes": "Full share settled"
  },
  {
    "id": "pay_aug_1",
    "month": "August 2026",
    "date": "31 Aug 26",
    "person": "Kitkat",
    "amount": 4567.42,
    "paymentMethod": "Bank Transfer",
    "notes": "Share payment"
  },
  {
    "id": "pay_aug_2",
    "month": "August 2026",
    "date": "31 Aug 26",
    "person": "Rashu",
    "amount": 0,
    "paymentMethod": "",
    "notes": "Pending"
  }
];

const INITIAL_UPI_EXPENSES = [
  {
    "id": "upi_aug_1",
    "month": "August 2026",
    "date": "01 Aug 26",
    "description": "Diy Mirror",
    "amount": 950,
    "usedBy": "Kitkat",
    "paidBy": "Rashu",
    "category": "Shopping",
    "remarks": ""
  },
  {
    "id": "upi_aug_2",
    "month": "August 2026",
    "date": "01 Aug 26",
    "description": "Diy rest",
    "amount": 1121,
    "usedBy": "Rashu",
    "paidBy": "Rashu",
    "category": "Shopping",
    "remarks": ""
  },
  {
    "id": "upi_aug_3",
    "month": "August 2026",
    "date": "01 Aug 26",
    "description": "Car service",
    "amount": 500,
    "usedBy": "Kitkat",
    "paidBy": "Rashu",
    "category": "Travel",
    "remarks": ""
  },
  {
    "id": "upi_aug_4",
    "month": "August 2026",
    "date": "01 Aug 26",
    "description": "sandals",
    "amount": 200,
    "usedBy": "Kitkat",
    "paidBy": "Rashu",
    "category": "Shopping",
    "remarks": ""
  },
  {
    "id": "upi_aug_5",
    "month": "August 2026",
    "date": "01 Aug 26",
    "description": "belt",
    "amount": 220,
    "usedBy": "Rashu",
    "paidBy": "Rashu",
    "category": "Shopping",
    "remarks": ""
  },
  {
    "id": "upi_aug_6",
    "month": "August 2026",
    "date": "01 Aug 26",
    "description": "Stall",
    "amount": 150,
    "usedBy": "Rashu",
    "paidBy": "Rashu",
    "category": "Food & Dining",
    "remarks": ""
  },
  {
    "id": "upi_aug_7",
    "month": "August 2026",
    "date": "01 Aug 26",
    "description": "mosi bangles",
    "amount": 300,
    "usedBy": "Rashu",
    "paidBy": "Rashu",
    "category": "Shopping",
    "remarks": ""
  },
  {
    "id": "upi_aug_8",
    "month": "August 2026",
    "date": "01 Aug 26",
    "description": "Rashu dress",
    "amount": 600,
    "usedBy": "Rashu",
    "paidBy": "Rashu",
    "category": "Shopping",
    "remarks": ""
  },
  {
    "id": "upi_aug_9",
    "month": "August 2026",
    "date": "01 Aug 26",
    "description": "Aru tshit",
    "amount": 250,
    "usedBy": "Rashu",
    "paidBy": "Rashu",
    "category": "Shopping",
    "remarks": ""
  },
  {
    "id": "upi_aug_10",
    "month": "August 2026",
    "date": "01 Aug 26",
    "description": "Papa Shirt",
    "amount": 550,
    "usedBy": "Rashu",
    "paidBy": "Rashu",
    "category": "Shopping",
    "remarks": ""
  },
  {
    "id": "upi_aug_11",
    "month": "August 2026",
    "date": "01 Aug 26",
    "description": "Rashu Watch",
    "amount": 250,
    "usedBy": "Rashu",
    "paidBy": "Rashu",
    "category": "Shopping",
    "remarks": ""
  }
];

const AVAILABLE_MONTHS = [
  "September 2026",
  "August 2026",
  "July 2026"
];

// Export to window for vanilla browser usage
window.DEFAULT_SETTINGS = DEFAULT_SETTINGS;
window.CATEGORIES = CATEGORIES;
window.INITIAL_EXPENSES = INITIAL_EXPENSES;
window.INITIAL_UPI_EXPENSES = INITIAL_UPI_EXPENSES;
window.INITIAL_PAYMENTS = INITIAL_PAYMENTS;
window.AVAILABLE_MONTHS = AVAILABLE_MONTHS;
